name: public-api diff on branch

on:
  pull_request_target:
    types:
      - labeled
      - synchronize
      - opened
      - reopened
    branches:
      - master

jobs:
  site-public-api-branch:
    if: |
      contains(github.event.pull_request.labels.*.name, 'generate-public-api-diff') ||
      github.event.label.name == 'generate-public-api-diff'

    permissions:
      contents: write
      pull-requests: write

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - name: Build public-api diff report for PR
        run: nix --extra-experimental-features "nix-command flakes" run .#cargo-public-api --color=never diff master..HEAD > 'public-api-diff.txt'

          #- name: Comment public-api diff to PR
          #  uses: peter-evans/create-or-update-comment@v4
          #  id: header
          #  with:
          #    token: ${{ secrets.GITHUB_TOKEN }}
          #    issue-number: ${{ github.event.pull_request.number }}
          #    body: |
          #      `cargo-public-api` diff against `master`:

      - name: Comment public-api diff to PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          #comment-id: ${{ steps.header.outputs.comment-id }}
          #edit-mode: append
          #append-seperator: newline
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: 'public-api-diff.txt'


