name: Site

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  site-deny-master:
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    # if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v14
        with:
          name: matthiasbeyer-actions-to-website
          # If you chose API tokens for write access OR if you have a private cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build coverage report for master
        run: nix --extra-experimental-features "nix-command flakes" run --print-build-logs .#denyReport

      - name: Deploy coverage report for master
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site/_data/denyreport/
          destination_dir: _data/denyreport/
          keep_files: true
          commit_message: Deploy deny report for master commit ${{ github.sha }}

      - name: Build site
        run: nix --extra-experimental-features "nix-command flakes" run .#buildSite

      - name: Deploy coverage report for master
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/
          keep_files: true
          commit_message: Deploy deny report for master commit ${{ github.sha }}

  site-coverage-master:
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v14
        with:
          name: matthiasbeyer-actions-to-website
          # If you chose API tokens for write access OR if you have a private cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build coverage report for master
        run: nix --extra-experimental-features "nix-command flakes" build .#coverage

      - name: Deploy coverage report for master
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result/
          destination_dir: llvmcov/${{ github.sha }}
          keep_files: true
          commit_message: Deploy coverage report for master commit ${{ github.event.head_commit.after }}

  site:
    needs:
      - site-coverage-master
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # so we can generate the coverage list links

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v14
        with:
          name: matthiasbeyer-actions-to-website
          # If you chose API tokens for write access OR if you have a private cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build coverageLinkList generator
        run: nix --extra-experimental-features "nix-command flakes" build --no-link .#coverageLinkList

      - name: Update coverage list
        run: |
          nix --extra-experimental-features "nix-command flakes" build .#coverageLinkList
          PATH=./result/bin:$PATH bash ./scripts/update_coverage_list.sh

      - name: Build site
        run: nix --extra-experimental-features "nix-command flakes" run .#buildSite

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/
          keep_files: true
          commit_message: Deploy website from commit ${{ github.event.head_commit.after }}

