name: Site

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  site-coverage-master:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v15
        with:
          name: matthiasbeyer-actions-to-website
          # If you chose API tokens for write access OR if you have a private cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build coverage report for master
        run: nix --extra-experimental-features "nix-command flakes" build .#coverage

      - name: Deploy coverage report for master
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result/
          destination_dir: llvmcov/${{ github.sha }}
          keep_files: true
          commit_message: Deploy coverage report for master commit ${{ github.event.head_commit.after }}

  site-bloat-master:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v15
        with:
          name: matthiasbeyer-actions-to-website
          # If you chose API tokens for write access OR if you have a private cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build bloat report for master
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git fetch origin "refs/notes/*:refs/notes/*"
          nix --extra-experimental-features "nix-command flakes" develop -c ruby ./scripts/create-bloat-report.rb > bloat.json
          git notes --ref refs/notes/cargo-bloat-report add --file bloat.json "${GITHUB_SHA}"
          git push origin "refs/notes/*"

  site:
    needs:
      - site-coverage-master
      - site-bloat-master
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # so we can generate the coverage list links

      - name: Fetch git-notes
        run: git fetch origin refs/notes/cargo-bloat-report:refs/notes/cargo-bloat-report

      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v15
        with:
          name: matthiasbeyer-actions-to-website
          # If you chose API tokens for write access OR if you have a private cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build site
        run: nix --extra-experimental-features "nix-command flakes" run .#buildSiteFull -- compile -V --env=ghpages

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/output
          keep_files: true
          commit_message: Deploy website from commit ${{ github.event.head_commit.after }}

